# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(1138, 785)
        self.tabWidget = QtWidgets.QTabWidget(gui)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 471, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 120, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 80, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 131, 21))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 161, 21))
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(200, 241, 201, 41))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(200, 210, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 370, 451, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 10, 411, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_5.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_5.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_6.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_6.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_6.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_6.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_6.addWidget(self.checkBox_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 179, 351))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color : orange; \n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.og_target_angle_spinbox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.og_target_angle_spinbox.setObjectName("og_target_angle_spinbox")
        self.verticalLayout.addWidget(self.og_target_angle_spinbox)
        self.og_target_angle_dial = QtWidgets.QDial(self.layoutWidget1)
        self.og_target_angle_dial.setObjectName("og_target_angle_dial")
        self.verticalLayout.addWidget(self.og_target_angle_dial)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.og_actual_angle_spinbox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.og_actual_angle_spinbox.setEnabled(False)
        self.og_actual_angle_spinbox.setObjectName("og_actual_angle_spinbox")
        self.verticalLayout_2.addWidget(self.og_actual_angle_spinbox)
        self.og_actual_angle_dial = QtWidgets.QDial(self.layoutWidget1)
        self.og_actual_angle_dial.setEnabled(False)
        self.og_actual_angle_dial.setObjectName("og_actual_angle_dial")
        self.verticalLayout_2.addWidget(self.og_actual_angle_dial)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel {\n"
"    color : green; \n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_9.addWidget(self.pushButton_8)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gg_target_angle_spinbox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.gg_target_angle_spinbox.setObjectName("gg_target_angle_spinbox")
        self.verticalLayout_11.addWidget(self.gg_target_angle_spinbox)
        self.gg_target_angle_dial = QtWidgets.QDial(self.layoutWidget1)
        self.gg_target_angle_dial.setObjectName("gg_target_angle_dial")
        self.verticalLayout_11.addWidget(self.gg_target_angle_dial)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gg_actual_angle_spinbox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.gg_actual_angle_spinbox.setEnabled(False)
        self.gg_actual_angle_spinbox.setObjectName("gg_actual_angle_spinbox")
        self.verticalLayout_10.addWidget(self.gg_actual_angle_spinbox)
        self.gg_actual_angle_dial = QtWidgets.QDial(self.layoutWidget1)
        self.gg_actual_angle_dial.setEnabled(False)
        self.gg_actual_angle_dial.setObjectName("gg_actual_angle_dial")
        self.verticalLayout_10.addWidget(self.gg_actual_angle_dial)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(190, 10, 280, 351))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QLabel {\n"
"    color: blue; \n"
"}")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_21.addWidget(self.label_27)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.wpp_target_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.wpp_target_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.wpp_target_upper_verticalSlider.setObjectName("wpp_target_upper_verticalSlider")
        self.verticalLayout_14.addWidget(self.wpp_target_upper_verticalSlider)
        self.wpp_target_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.wpp_target_lower_verticalSlider.setMinimum(0)
        self.wpp_target_lower_verticalSlider.setMaximum(99)
        self.wpp_target_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.wpp_target_lower_verticalSlider.setInvertedAppearance(True)
        self.wpp_target_lower_verticalSlider.setInvertedControls(False)
        self.wpp_target_lower_verticalSlider.setObjectName("wpp_target_lower_verticalSlider")
        self.verticalLayout_14.addWidget(self.wpp_target_lower_verticalSlider)
        self.wpp_target_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.wpp_target_spinBox.setObjectName("wpp_target_spinBox")
        self.verticalLayout_14.addWidget(self.wpp_target_spinBox)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.wpp_actual_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.wpp_actual_upper_verticalSlider.setEnabled(False)
        self.wpp_actual_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.wpp_actual_upper_verticalSlider.setObjectName("wpp_actual_upper_verticalSlider")
        self.verticalLayout_15.addWidget(self.wpp_actual_upper_verticalSlider)
        self.wpp_actual_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.wpp_actual_lower_verticalSlider.setEnabled(False)
        self.wpp_actual_lower_verticalSlider.setMinimum(0)
        self.wpp_actual_lower_verticalSlider.setMaximum(99)
        self.wpp_actual_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.wpp_actual_lower_verticalSlider.setInvertedAppearance(True)
        self.wpp_actual_lower_verticalSlider.setInvertedControls(False)
        self.wpp_actual_lower_verticalSlider.setObjectName("wpp_actual_lower_verticalSlider")
        self.verticalLayout_15.addWidget(self.wpp_actual_lower_verticalSlider)
        self.wpp_actual_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.wpp_actual_spinBox.setEnabled(False)
        self.wpp_actual_spinBox.setObjectName("wpp_actual_spinBox")
        self.verticalLayout_15.addWidget(self.wpp_actual_spinBox)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.spp_target_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.spp_target_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.spp_target_upper_verticalSlider.setObjectName("spp_target_upper_verticalSlider")
        self.verticalLayout_19.addWidget(self.spp_target_upper_verticalSlider)
        self.spp_target_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.spp_target_lower_verticalSlider.setMinimum(0)
        self.spp_target_lower_verticalSlider.setMaximum(99)
        self.spp_target_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.spp_target_lower_verticalSlider.setInvertedAppearance(True)
        self.spp_target_lower_verticalSlider.setInvertedControls(False)
        self.spp_target_lower_verticalSlider.setObjectName("spp_target_lower_verticalSlider")
        self.verticalLayout_19.addWidget(self.spp_target_lower_verticalSlider)
        self.spp_target_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spp_target_spinBox.setObjectName("spp_target_spinBox")
        self.verticalLayout_19.addWidget(self.spp_target_spinBox)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_19.addWidget(self.label_25)
        self.horizontalLayout_9.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.spp_actual_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.spp_actual_upper_verticalSlider.setEnabled(False)
        self.spp_actual_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.spp_actual_upper_verticalSlider.setObjectName("spp_actual_upper_verticalSlider")
        self.verticalLayout_20.addWidget(self.spp_actual_upper_verticalSlider)
        self.spp_actual_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.spp_actual_lower_verticalSlider.setEnabled(False)
        self.spp_actual_lower_verticalSlider.setMinimum(0)
        self.spp_actual_lower_verticalSlider.setMaximum(99)
        self.spp_actual_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.spp_actual_lower_verticalSlider.setInvertedAppearance(True)
        self.spp_actual_lower_verticalSlider.setInvertedControls(False)
        self.spp_actual_lower_verticalSlider.setObjectName("spp_actual_lower_verticalSlider")
        self.verticalLayout_20.addWidget(self.spp_actual_lower_verticalSlider)
        self.spp_actual_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spp_actual_spinBox.setEnabled(False)
        self.spp_actual_spinBox.setObjectName("spp_actual_spinBox")
        self.verticalLayout_20.addWidget(self.spp_actual_spinBox)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_20.addWidget(self.label_26)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.xpp_target_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.xpp_target_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.xpp_target_upper_verticalSlider.setObjectName("xpp_target_upper_verticalSlider")
        self.verticalLayout_16.addWidget(self.xpp_target_upper_verticalSlider)
        self.xpp_target_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.xpp_target_lower_verticalSlider.setMinimum(0)
        self.xpp_target_lower_verticalSlider.setMaximum(99)
        self.xpp_target_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.xpp_target_lower_verticalSlider.setInvertedAppearance(True)
        self.xpp_target_lower_verticalSlider.setInvertedControls(False)
        self.xpp_target_lower_verticalSlider.setObjectName("xpp_target_lower_verticalSlider")
        self.verticalLayout_16.addWidget(self.xpp_target_lower_verticalSlider)
        self.xpp_target_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.xpp_target_spinBox.setObjectName("xpp_target_spinBox")
        self.verticalLayout_16.addWidget(self.xpp_target_spinBox)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_16.addWidget(self.label_20)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.xpp_actual_upper_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.xpp_actual_upper_verticalSlider.setEnabled(False)
        self.xpp_actual_upper_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.xpp_actual_upper_verticalSlider.setObjectName("xpp_actual_upper_verticalSlider")
        self.verticalLayout_17.addWidget(self.xpp_actual_upper_verticalSlider)
        self.xpp_actual_lower_verticalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.xpp_actual_lower_verticalSlider.setEnabled(False)
        self.xpp_actual_lower_verticalSlider.setMinimum(0)
        self.xpp_actual_lower_verticalSlider.setMaximum(99)
        self.xpp_actual_lower_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.xpp_actual_lower_verticalSlider.setInvertedAppearance(True)
        self.xpp_actual_lower_verticalSlider.setInvertedControls(False)
        self.xpp_actual_lower_verticalSlider.setObjectName("xpp_actual_lower_verticalSlider")
        self.verticalLayout_17.addWidget(self.xpp_actual_lower_verticalSlider)
        self.xpp_actual_spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.xpp_actual_spinBox.setEnabled(False)
        self.xpp_actual_spinBox.setObjectName("xpp_actual_spinBox")
        self.verticalLayout_17.addWidget(self.xpp_actual_spinBox)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_17.addWidget(self.label_21)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_21.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.debug_scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.debug_scrollArea.setGeometry(QtCore.QRect(10, 10, 1, 1))
        self.debug_scrollArea.setWidgetResizable(True)
        self.debug_scrollArea.setObjectName("debug_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 16, 16))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.debug_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 441, 431))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_22.addWidget(self.label_8)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget3)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout_22.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_3, "")
        self.openGLWidget = QtWidgets.QOpenGLWidget(gui)
        self.openGLWidget.setGeometry(QtCore.QRect(490, 450, 641, 251))
        self.openGLWidget.setObjectName("openGLWidget")
        self.graphicsView = QtWidgets.QGraphicsView(gui)
        self.graphicsView.setGeometry(QtCore.QRect(490, 60, 640, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(gui)
        self.label.setGeometry(QtCore.QRect(490, 420, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(gui)
        self.label_2.setGeometry(QtCore.QRect(490, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(gui)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(gui)
        self.label_4.setGeometry(QtCore.QRect(10, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.treeWidget = QtWidgets.QTreeWidget(gui)
        self.treeWidget.setGeometry(QtCore.QRect(10, 550, 470, 131))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.label_6 = QtWidgets.QLabel(gui)
        self.label_6.setGeometry(QtCore.QRect(10, 680, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(gui)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 710, 831, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget4 = QtWidgets.QWidget(gui)
        self.layoutWidget4.setGeometry(QtCore.QRect(850, 710, 281, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.progressBar_2 = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar_2.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: blue;\n"
"    width: 1px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 0px;\n"
"    text-align: center;    \n"
"}\n"
"")
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_2.addWidget(self.progressBar_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: #3add36;\n"
"    width: 1px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.layoutWidget5 = QtWidgets.QWidget(gui)
        self.layoutWidget5.setGeometry(QtCore.QRect(610, 20, 281, 41))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget5)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 31, 17))
        self.radioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 20, 31, 17))
        self.radioButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(70, 20, 31, 17))
        self.radioButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)

        self.retranslateUi(gui)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "CHAMP GUI"))
        self.pushButton_3.setText(_translate("gui", "Gait Up Tree"))
        self.pushButton_4.setText(_translate("gui", "Gait Down Tree"))
        self.pushButton_5.setText(_translate("gui", "Gait Left"))
        self.pushButton_6.setText(_translate("gui", "Gait Right"))
        self.groupBox_2.setTitle(_translate("gui", "Gait Mode"))
        self.radioButton_4.setText(_translate("gui", "Inchworm"))
        self.radioButton_5.setText(_translate("gui", "Rotating Climb"))
        self.radioButton_6.setText(_translate("gui", "Hybrid"))
        self.label_5.setText(_translate("gui", "Speed Factor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gui", "Beginner"))
        self.checkBox.setText(_translate("gui", "CheckBox"))
        self.checkBox_2.setText(_translate("gui", "CheckBox"))
        self.checkBox_3.setText(_translate("gui", "CheckBox"))
        self.checkBox_4.setText(_translate("gui", "CheckBox"))
        self.checkBox_5.setText(_translate("gui", "CheckBox"))
        self.checkBox_6.setText(_translate("gui", "CheckBox"))
        self.checkBox_7.setText(_translate("gui", "CheckBox"))
        self.checkBox_8.setText(_translate("gui", "CheckBox"))
        self.checkBox_9.setText(_translate("gui", "CheckBox"))
        self.checkBox_10.setText(_translate("gui", "CheckBox"))
        self.label_16.setText(_translate("gui", "Orange Gripper"))
        self.pushButton_7.setText(_translate("gui", "Toggle Grip"))
        self.label_17.setText(_translate("gui", "Gripper\n"
"Angle"))
        self.label_10.setText(_translate("gui", "Target"))
        self.label_11.setText(_translate("gui", "Actual"))
        self.label_22.setText(_translate("gui", "Green Gripper"))
        self.pushButton_8.setText(_translate("gui", "Toggle Grip"))
        self.label_23.setText(_translate("gui", "Gripper\n"
"Angle"))
        self.label_13.setText(_translate("gui", "Target"))
        self.label_12.setText(_translate("gui", "Actual"))
        self.label_27.setText(_translate("gui", "Push-Pull Rods"))
        self.label_14.setText(_translate("gui", "W Push-Pull"))
        self.label_18.setText(_translate("gui", "Target"))
        self.label_15.setText(_translate("gui", "Actual"))
        self.label_24.setText(_translate("gui", "Spine PP"))
        self.label_25.setText(_translate("gui", "Target"))
        self.label_26.setText(_translate("gui", "Actual"))
        self.label_19.setText(_translate("gui", "X Push-Pull"))
        self.label_20.setText(_translate("gui", "Target"))
        self.label_21.setText(_translate("gui", "Actual"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gui", "Expert"))
        self.label_8.setText(_translate("gui", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("gui", "Debug"))
        self.label.setText(_translate("gui", "Robot Rendering"))
        self.label_2.setText(_translate("gui", "Camera View"))
        self.label_3.setText(_translate("gui", "Controls"))
        self.label_4.setText(_translate("gui", "Display"))
        self.treeWidget.headerItem().setText(0, _translate("gui", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("gui", "Value"))
        self.treeWidget.headerItem().setText(2, _translate("gui", "Unit"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("gui", "Gripper 1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("gui", "Motors"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("gui", "Rotation Motor"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("gui", "Rotation"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(2, _translate("gui", "Degrees"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("gui", "Current"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(2, _translate("gui", "Amps"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("gui", "Grip Motor"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("gui", "Rotation"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(2, _translate("gui", "Degrees"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).setText(0, _translate("gui", "Current"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).setText(2, _translate("gui", "Amps"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("gui", "IMU"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("gui", "Roll"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(2, _translate("gui", "Degrees"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("gui", "Pitch"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(2, _translate("gui", "Degrees"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("gui", "Heading"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(1, _translate("gui", "Value"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(2, _translate("gui", "Degrees"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("gui", "Abdomen"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("gui", "Gripper 2"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("gui", "Status Monitor"))
        self.label_9.setText(_translate("gui", "Wireless Signal Strength"))
        self.label_7.setText(_translate("gui", "Battery"))
        self.pushButton.setText(_translate("gui", "Prev. View"))
        self.groupBox.setTitle(_translate("gui", "Camera Angle"))
        self.radioButton.setText(_translate("gui", "1"))
        self.radioButton_2.setText(_translate("gui", "2"))
        self.radioButton_3.setText(_translate("gui", "3"))
        self.pushButton_2.setText(_translate("gui", "Next View"))

