# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_view.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gui_view(object):
    def setupUi(self, gui_view):
        gui_view.setObjectName("gui_view")
        gui_view.resize(898, 300)
        self.leftStickX_verticalSlider = QtWidgets.QSlider(gui_view)
        self.leftStickX_verticalSlider.setGeometry(QtCore.QRect(50, 250, 160, 22))
        self.leftStickX_verticalSlider.setMinimum(-100)
        self.leftStickX_verticalSlider.setMaximum(100)
        self.leftStickX_verticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftStickX_verticalSlider.setObjectName("leftStickX_verticalSlider")
        self.leftStickY_verticalSlider = QtWidgets.QSlider(gui_view)
        self.leftStickY_verticalSlider.setGeometry(QtCore.QRect(30, 50, 22, 200))
        self.leftStickY_verticalSlider.setMinimum(-100)
        self.leftStickY_verticalSlider.setMaximum(100)
        self.leftStickY_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.leftStickY_verticalSlider.setObjectName("leftStickY_verticalSlider")
        self.label = QtWidgets.QLabel(gui_view)
        self.label.setGeometry(QtCore.QRect(90, 10, 90, 40))
        self.label.setObjectName("label")
        self.rightStickY_verticalSlider = QtWidgets.QSlider(gui_view)
        self.rightStickY_verticalSlider.setGeometry(QtCore.QRect(250, 50, 22, 200))
        self.rightStickY_verticalSlider.setMinimum(-100)
        self.rightStickY_verticalSlider.setMaximum(100)
        self.rightStickY_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.rightStickY_verticalSlider.setObjectName("rightStickY_verticalSlider")
        self.rightStickX_verticalSlider = QtWidgets.QSlider(gui_view)
        self.rightStickX_verticalSlider.setGeometry(QtCore.QRect(270, 250, 160, 22))
        self.rightStickX_verticalSlider.setMinimum(-100)
        self.rightStickX_verticalSlider.setMaximum(100)
        self.rightStickX_verticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightStickX_verticalSlider.setObjectName("rightStickX_verticalSlider")
        self.label_2 = QtWidgets.QLabel(gui_view)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 90, 40))
        self.label_2.setObjectName("label_2")
        self.leftStrick_pushButton = QtWidgets.QPushButton(gui_view)
        self.leftStrick_pushButton.setGeometry(QtCore.QRect(90, 140, 75, 60))
        self.leftStrick_pushButton.setObjectName("leftStrick_pushButton")
        self.rightStick_pushButton = QtWidgets.QPushButton(gui_view)
        self.rightStick_pushButton.setGeometry(QtCore.QRect(310, 140, 75, 60))
        self.rightStick_pushButton.setObjectName("rightStick_pushButton")
        self.leftBumper_pushButton = QtWidgets.QPushButton(gui_view)
        self.leftBumper_pushButton.setGeometry(QtCore.QRect(90, 80, 75, 23))
        self.leftBumper_pushButton.setObjectName("leftBumper_pushButton")
        self.rightBumper_pushButton = QtWidgets.QPushButton(gui_view)
        self.rightBumper_pushButton.setGeometry(QtCore.QRect(310, 80, 75, 23))
        self.rightBumper_pushButton.setObjectName("rightBumper_pushButton")
        self.y_pushButton = QtWidgets.QPushButton(gui_view)
        self.y_pushButton.setGeometry(QtCore.QRect(630, 60, 30, 23))
        self.y_pushButton.setObjectName("y_pushButton")
        self.a_pushButton = QtWidgets.QPushButton(gui_view)
        self.a_pushButton.setGeometry(QtCore.QRect(630, 120, 30, 23))
        self.a_pushButton.setObjectName("a_pushButton")
        self.b_pushButton = QtWidgets.QPushButton(gui_view)
        self.b_pushButton.setGeometry(QtCore.QRect(660, 90, 30, 23))
        self.b_pushButton.setObjectName("b_pushButton")
        self.x_pushButton = QtWidgets.QPushButton(gui_view)
        self.x_pushButton.setGeometry(QtCore.QRect(600, 90, 30, 23))
        self.x_pushButton.setObjectName("x_pushButton")
        self.label_3 = QtWidgets.QLabel(gui_view)
        self.label_3.setGeometry(QtCore.QRect(590, 10, 111, 40))
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(gui_view)
        self.pushButton_7.setGeometry(QtCore.QRect(660, 230, 30, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_4 = QtWidgets.QLabel(gui_view)
        self.label_4.setGeometry(QtCore.QRect(590, 160, 111, 40))
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtWidgets.QPushButton(gui_view)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 260, 30, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(gui_view)
        self.pushButton_9.setGeometry(QtCore.QRect(600, 230, 30, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(gui_view)
        self.pushButton_10.setGeometry(QtCore.QRect(630, 200, 30, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.rightTrigger_verticalSlide = QtWidgets.QSlider(gui_view)
        self.rightTrigger_verticalSlide.setGeometry(QtCore.QRect(470, 60, 22, 191))
        self.rightTrigger_verticalSlide.setOrientation(QtCore.Qt.Vertical)
        self.rightTrigger_verticalSlide.setObjectName("rightTrigger_verticalSlide")
        self.leftTrigger_verticalSlide = QtWidgets.QSlider(gui_view)
        self.leftTrigger_verticalSlide.setGeometry(QtCore.QRect(530, 60, 22, 191))
        self.leftTrigger_verticalSlide.setOrientation(QtCore.Qt.Vertical)
        self.leftTrigger_verticalSlide.setObjectName("leftTrigger_verticalSlide")
        self.label_5 = QtWidgets.QLabel(gui_view)
        self.label_5.setGeometry(QtCore.QRect(460, 10, 91, 40))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(gui_view)
        self.label_6.setGeometry(QtCore.QRect(460, 270, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(gui_view)
        self.label_7.setGeometry(QtCore.QRect(520, 270, 41, 21))
        self.label_7.setObjectName("label_7")
        self.start_pushButton = QtWidgets.QPushButton(gui_view)
        self.start_pushButton.setGeometry(QtCore.QRect(770, 60, 75, 23))
        self.start_pushButton.setObjectName("start_pushButton")
        self.label_9 = QtWidgets.QLabel(gui_view)
        self.label_9.setGeometry(QtCore.QRect(740, 10, 131, 40))
        self.label_9.setObjectName("label_9")
        self.back_pushButton = QtWidgets.QPushButton(gui_view)
        self.back_pushButton.setGeometry(QtCore.QRect(770, 90, 75, 23))
        self.back_pushButton.setObjectName("back_pushButton")

        self.retranslateUi(gui_view)
        QtCore.QMetaObject.connectSlotsByName(gui_view)

    def retranslateUi(self, gui_view):
        _translate = QtCore.QCoreApplication.translate
        gui_view.setWindowTitle(_translate("gui_view", "CHAMP GUI"))
        self.label.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Left Stick</span></p></body></html>"))
        self.label_2.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Right Stick</span></p></body></html>"))
        self.leftStrick_pushButton.setText(_translate("gui_view", "Left Stick\n"
"Button"))
        self.rightStick_pushButton.setText(_translate("gui_view", "Right Stick\n"
"Button"))
        self.leftBumper_pushButton.setText(_translate("gui_view", "Left Bumper"))
        self.rightBumper_pushButton.setText(_translate("gui_view", "Right Bumper"))
        self.y_pushButton.setText(_translate("gui_view", "Y"))
        self.a_pushButton.setText(_translate("gui_view", "A"))
        self.b_pushButton.setText(_translate("gui_view", "B"))
        self.x_pushButton.setText(_translate("gui_view", "X"))
        self.label_3.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Face Buttons</span></p></body></html>"))
        self.pushButton_7.setText(_translate("gui_view", "B"))
        self.label_4.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">D Pad</span></p></body></html>"))
        self.pushButton_8.setText(_translate("gui_view", "A"))
        self.pushButton_9.setText(_translate("gui_view", "X"))
        self.pushButton_10.setText(_translate("gui_view", "Y"))
        self.label_5.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Triggers</span></p></body></html>"))
        self.label_6.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Left</span></p></body></html>"))
        self.label_7.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Right</span></p></body></html>"))
        self.start_pushButton.setText(_translate("gui_view", "Start"))
        self.label_9.setText(_translate("gui_view", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Special Buttons</span></p></body></html>"))
        self.back_pushButton.setText(_translate("gui_view", "Back"))

