# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_view.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gui_view(object):
    def setupUi(self, gui_view):
        gui_view.setObjectName("gui_view")
        gui_view.resize(461, 651)
        self.leftExtruder1_verticalSlider = QtWidgets.QSlider(gui_view)
        self.leftExtruder1_verticalSlider.setGeometry(QtCore.QRect(30, 140, 22, 160))
        self.leftExtruder1_verticalSlider.setMinimum(-100)
        self.leftExtruder1_verticalSlider.setMaximum(100)
        self.leftExtruder1_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.leftExtruder1_verticalSlider.setObjectName("leftExtruder1_verticalSlider")
        self.leftExtruder2_verticalSlider = QtWidgets.QSlider(gui_view)
        self.leftExtruder2_verticalSlider.setGeometry(QtCore.QRect(30, 310, 22, 160))
        self.leftExtruder2_verticalSlider.setMinimum(-100)
        self.leftExtruder2_verticalSlider.setMaximum(100)
        self.leftExtruder2_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.leftExtruder2_verticalSlider.setObjectName("leftExtruder2_verticalSlider")
        self.dial = QtWidgets.QDial(gui_view)
        self.dial.setGeometry(QtCore.QRect(50, 70, 50, 64))
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(gui_view)
        self.dial_2.setGeometry(QtCore.QRect(50, 470, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.dial_3 = QtWidgets.QDial(gui_view)
        self.dial_3.setGeometry(QtCore.QRect(50, 20, 50, 64))
        self.dial_3.setObjectName("dial_3")
        self.dial_4 = QtWidgets.QDial(gui_view)
        self.dial_4.setGeometry(QtCore.QRect(50, 520, 50, 64))
        self.dial_4.setAcceptDrops(False)
        self.dial_4.setObjectName("dial_4")
        self.middleExtruder2_verticalSlider = QtWidgets.QSlider(gui_view)
        self.middleExtruder2_verticalSlider.setGeometry(QtCore.QRect(70, 310, 22, 160))
        self.middleExtruder2_verticalSlider.setMinimum(-100)
        self.middleExtruder2_verticalSlider.setMaximum(100)
        self.middleExtruder2_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.middleExtruder2_verticalSlider.setObjectName("middleExtruder2_verticalSlider")
        self.middleExtruder1_verticalSlider = QtWidgets.QSlider(gui_view)
        self.middleExtruder1_verticalSlider.setGeometry(QtCore.QRect(70, 140, 22, 160))
        self.middleExtruder1_verticalSlider.setMinimum(-100)
        self.middleExtruder1_verticalSlider.setMaximum(100)
        self.middleExtruder1_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.middleExtruder1_verticalSlider.setObjectName("middleExtruder1_verticalSlider")
        self.rightExtruder2_verticalSlider = QtWidgets.QSlider(gui_view)
        self.rightExtruder2_verticalSlider.setGeometry(QtCore.QRect(110, 310, 22, 160))
        self.rightExtruder2_verticalSlider.setMinimum(-100)
        self.rightExtruder2_verticalSlider.setMaximum(100)
        self.rightExtruder2_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.rightExtruder2_verticalSlider.setObjectName("rightExtruder2_verticalSlider")
        self.rightExtruder1_verticalSlider = QtWidgets.QSlider(gui_view)
        self.rightExtruder1_verticalSlider.setGeometry(QtCore.QRect(110, 140, 22, 160))
        self.rightExtruder1_verticalSlider.setMinimum(-100)
        self.rightExtruder1_verticalSlider.setMaximum(100)
        self.rightExtruder1_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.rightExtruder1_verticalSlider.setObjectName("rightExtruder1_verticalSlider")
        self.label = QtWidgets.QLabel(gui_view)
        self.label.setGeometry(QtCore.QRect(120, 30, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(gui_view)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(gui_view)
        self.label_3.setGeometry(QtCore.QRect(120, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(gui_view)
        self.label_4.setGeometry(QtCore.QRect(120, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(gui_view)
        QtCore.QMetaObject.connectSlotsByName(gui_view)

    def retranslateUi(self, gui_view):
        _translate = QtCore.QCoreApplication.translate
        gui_view.setWindowTitle(_translate("gui_view", "CHAMP GUI"))
        self.label.setText(_translate("gui_view", "Gripper 1"))
        self.label_2.setText(_translate("gui_view", "Rotato 1"))
        self.label_3.setText(_translate("gui_view", "Rotato 1"))
        self.label_4.setText(_translate("gui_view", "Gripper 1"))

